= Laconic Stream Utils

This is a library of laconic method-aliases for safety stream operations with collections in Java.

== Introduction

Java 8+ introduces Stream API & Optional classes, but sometimes the syntax is really verbose even for simple stream manipulations. This library introduces method-aliases for some popular operation with collections.

For example, instead of the following code:

[source,java]
----
if (users != null) {
    return users.stream().map(User::getFirstName).collect(Collectors.toList());
}
return new ArrayList<>();
----

you can use short static method from the `Lists` class:

[source,java]
----
return map(users, User::getFirstName);
----

== Installation

Min Requirements: JDK 8+

You can pull releases from the Maven Central repository:
https://search.maven.org/artifact/io.github.avegera/stream-utils

Use the following dependency for Maven/Gradle:

[tabs]
====
Maven::
+
[source,xml]
----
<dependency>
    <groupId>io.github.avegera</groupId>
    <artifactId>stream-utils</artifactId>
    <version>0.2.0</version>
</dependency>
----

Gradle::
+
[source,groovy]
----
implementation 'io.github.avegera:stream-utils:0.2.0'
----
====

== Links

* User Guide - TBD

* https://www.javadoc.io/doc/io.github.avegera/stream-utils/latest/io/github/avegera/stream/utils/package-summary.html[JavaDoc]

* https://github.com/avegera/stream-utils/wiki[Wiki Documentation]

=== Streams
`Streams` contains NPE-safety methods for stream instantiating by provided input data. For example, the following method returns stream of users (or empty stream in case when `users == null`):

[source,java]
----
Stream<User> stream = safeStream(users);
----

=== Lists
`Lists` contains NPE-safety method-aliases for common Stream API intermediate operations like:

* map()
* filter()
* flatMap()
* distinct()
* sort()

By default, the result of operations is a `List`. Use suffix `...ToSet()` in method name to return `Set` instead. For example, the following method returns list of groups:

[source,java]
----
List<Group> groups = map(users, User::getGroup);
----

But this one returns set of groups:

[source,java]
----
Set<Group> groups = mapToSet(users, User::getGroup);
----

Aliases for terminal operations also available:

* collect(toList())
* collect(toSet())
* count()
* findFirst()
* findAny()
* allMatch()
* anyMatch()
* noneMatch()

For example, the following method returns first user from list or null if no users inside:

[source,java]
----
User user = findFirstOrNull(users);
----

== License

This project is published under the Apache License 2.0, see http://www.apache.org/licenses/LICENSE-2.0 for details.